"""
This script is the entry point for the Mario Expert agent. It creates an instance of the MarioExpert class and calls

Do NOT edit this file as it runs the evaluation methodology for the Mario Expert agent.
"""

import argparse
import logging
import os
from pathlib import Path

from mairo_expert import MarioExpert

logging.basicConfig(level=logging.INFO)


def get_args():
    parse_args = argparse.ArgumentParser()

    parse_args.add_argument("--headless", action="store_true")

    parse_args.add_argument("--upi", type=str, required=True)

    return parse_args.parse_args()


def run(upi, headless):
    results_path = f"{Path(__file__).parent.parent}/results/{upi}"
    logging.info(f"Saving data into: {results_path}")

    if not os.path.exists(results_path):
        os.makedirs(results_path)

    expert = MarioExpert(results_path=results_path, headless=headless)
    expert.play()


if __name__ == "__main__":
    args = get_args()

    upi = args.upi
    headless = args.headless
    run(upi, headless)
