"""
This script is the entry point for the Mario Expert agent. It creates an instance of the MarioExpert class and calls

Do NOT edit this file as it runs the evaluation methodology for the Mario Expert agent.
"""

import argparse
import logging
import os
from pathlib import Path

from mario_expert import MarioExpert

logging.basicConfig(level=logging.INFO)


def get_args():
    parse_args = argparse.ArgumentParser()

    parse_args.add_argument("--headless", action="store_true")

    parse_args.add_argument("--upi", type=str, required=True)

    return parse_args.parse_args()


def run(upi, headless):
    if upi == "your_upi":
        raise ValueError("Please set your UPI in the run.py file")

    results_path = f"{Path(__file__).parent.parent}/results/{upi}"
    logging.info(f"Saving data into: {results_path}")

    if not os.path.exists(results_path):
        os.makedirs(results_path)

    expert = MarioExpert(results_path=results_path, headless=headless)
    expert.play()


def main():
    args = get_args()

    run(args.upi, args.headless)


if __name__ == "__main__":
    main()
